language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq nodejs npm
script:
- cd ~/backend && sbt test
- cd ~/frontend && mvn install
- cd ~/frontend && gulp test
