ox: osx
language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
before_install:
- brew update
- brew install node
- brew install npm
script:
- cd ./backend && sbt test
- cd ../frontend && npm install && gulp test
